propel:
  database:
      connections:
          comicslist:
              adapter: mysql
              classname: Propel\Runtime\Connection\ConnectionWrapper
              dsn: "mysql:host=localhost;dbname=remygbdd3"
              user: root
              password: 
              attributes:
  runtime:
      defaultConnection: comicslist
      connections:
          - comicslist
  generator:
      defaultConnection: comicslist
      connections:
          - comicslist

